{"name": "test_login[data0]", "status": "failed", "statusDetails": {"message": "AssertionError: 登录失败: 用户不存在\nassert -1 == 0", "trace": "get_base_url = 'http://localhost:8080', data = {'name': 'test001', 'password': '123456'}\n\n    @pytest.mark.parametrize(\"data\", [\n        {\"name\": \"test001\", \"password\": \"123456\"},\n        {\"name\": \"test002\", \"password\": \"123456\"}\n    ])\n    def test_login(get_base_url, data):\n        \"\"\"\n        用户登录测试\n        \"\"\"\n        url = f\"{get_base_url}/user/findUserByNameAndPwd\"\n        resp = requests.post(url, params=data)\n        print(resp.text)\n        assert resp.status_code == 200\n        j = resp.json()\n>       assert j[\"code\"] == 0, f\"登录失败: {j['message']}\"\nE       AssertionError: 登录失败: 用户不存在\nE       assert -1 == 0\n\ntestcases\\test_user_login.py:18: AssertionError"}, "description": "\n    用户登录测试\n    ", "parameters": [{"name": "data", "value": "{'name': 'test001', 'password': '123456'}"}], "start": 1761034610073, "stop": 1761034610145, "uuid": "6f4cccaf-206a-4a41-96aa-2d4cbfece9b9", "historyId": "1a7eeada76a8eddd82d6ce3b0e63a4d6", "testCaseId": "ab4ae781b39039ec4eae113a075c2b68", "fullName": "testcases.test_user_login#test_login", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_user_login"}, {"name": "host", "value": "DESKTOP-UGQEI6T"}, {"name": "thread", "value": "26140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_user_login"}], "titlePath": ["testcases", "test_user_login.py"]}