{"name": "test_login[data1]", "status": "failed", "statusDetails": {"message": "AssertionError: 登录失败: 密码错误\nassert -1 == 0", "trace": "get_base_url = 'http://localhost:8080', data = {'name': 'test002', 'password': '123456'}\n\n    @pytest.mark.parametrize(\"data\", [\n        {\"name\": \"test001\", \"password\": \"123456\"},\n        {\"name\": \"test002\", \"password\": \"123456\"}\n    ])\n    def test_login(get_base_url, data):\n        \"\"\"\n        用户登录测试\n        \"\"\"\n        url = f\"{get_base_url}/user/findUserByNameAndPwd\"\n        resp = requests.post(url, params=data)\n        print(resp.text)\n        assert resp.status_code == 200\n        j = resp.json()\n>       assert j[\"code\"] == 0, f\"登录失败: {j['message']}\"\nE       AssertionError: 登录失败: 密码错误\nE       assert -1 == 0\n\ntestcases\\test_user_login.py:18: AssertionError"}, "description": "\n    用户登录测试\n    ", "parameters": [{"name": "data", "value": "{'name': 'test002', 'password': '123456'}"}], "start": 1761030489444, "stop": 1761030489449, "uuid": "0f58d7f9-d14d-4503-add1-085938bd5389", "historyId": "ef4e97727be586459ef7c24e8360cd74", "testCaseId": "ab4ae781b39039ec4eae113a075c2b68", "fullName": "testcases.test_user_login#test_login", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_user_login"}, {"name": "host", "value": "DESKTOP-UGQEI6T"}, {"name": "thread", "value": "26396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_user_login"}], "titlePath": ["testcases", "test_user_login.py"]}